name: "MyTube Dash - Peristent Edition"
version: "4.1.0"
slug: "mytubedash"
description: "Versiunea pură HTML/CSS."
arch:
  - amd64
  - aarch64
startup: application
boot: auto
ingress: true
ingress_port: 3000
panel_icon: mdi:youtube
panel_title: "MyTube Dash"
